magazin/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

magazin/magazin/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

magazin/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',
        views.order_create,
        name='order_create'),
]

magazin/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

magazin/cart/models.py
from django.db import models

# Create your models here.

magazin/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

magazin/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

magazin/cart/templates/cart/detail.html
{% extends "shop/base.html" %}

{% load static from staticfiles %}
{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}

<!--Shopping Cart table-->

    <div class="container">
<div class="table-responsive">
    <table class="table product-table">
        <!--Table head-->
        <thead>
            <tr>

                <th>Фото </th>
                <th>Товар</th>
                <th>    Удалить</th>

                 <th></th>
                <th>Кол-во</th>
                <th>Добавить</th>
                 <th>Цена</th>
                <th>Цена всего</th>


            </tr>
        </thead>
        <!--/Table head-->

        <!--Table body-->
        <tbody>
{% for item in cart %}
        {% with product=item.product %}
            <!--First row-->
            <tr>
                <th scope="row">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="" class="img-fluid">
                </th>
                <td>
                    <h5><strong>{{ product.name }}</strong></h5>
                    <p class="text-muted"></p>
                </td>

             <td><a  class="btn btn-primary-outline waves-effect btn-sm" href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
               <td><form action="{% url "cart:cart_add" product.id %}" method="post">

<label></label>
<td><select type="{{ cart_product_form }}" title="Добавить" id="id_quantity" name="quantity"  class="browser-default">
    <option value="{{ item.update_quantity_form.update }},{{ item.update_quantity_form.quantity }}">{{ item.quantity }}</option>

    <option value="1"> 1</option>
    <option value="2"> 2</option>
    <option value="3"> 3</option>
    <option value="4"> 4</option>
    <option value="5"> 5</option>
    <option value="6"> 6</option>
    <option value="7"> 7</option>
    <option value="8"> 8</option>
    <option value="9"> 9</option>
    <option value="10"> 10</option>

</select></td>


<td><button type="submit" class="btn btn-success-outline waves-effect btn-sm" >Добавить</button></td>

 {% csrf_token %}
            </form>
</td>
                <td class="num">{{ item.price }}руб</td>
            <td class="num">{{ item.total_price }}руб</td>
            </tr>
        {% endwith %}
      {% endfor %}
                <td>
                <td colspan="3"></td>
                <td>
                    <h4><strong>Итого</strong></h4></td>
                <td>
                    <h4><strong>{{ cart.get_total_price }}руб</strong></h4></td>
                <td colspan="3"><a href="{% url "orders:order_create" %}" class="btn btn-success-outline waves-effect btn-lg">Оплатить</a></td>


        </tbody>
        <!--/Table body-->
    </table>



</div>
    <div class="row">
        <div class="col-xs-12">

            <a href="{% url "shop:product_list" %}" class="btn btn-primary btn-lg btn-block">Продолжить покупки</a>
    </div>
        <div class="col-xs-12">

    </div>
<!--/Shopping Cart table-->
 </div>
    </div>
{% endblock %}